"""Deterministic generator for docs/assets/paa-walkthrough/.

Renders one reference execution of the ``scout paa`` control plane against
Scout's checked-in ``inbound_reply_surfacing`` declaration: the initial
position, a promotion proposal, its approval, a fail-closed evidence
verification failure, rejection of that stale proposal, an emergency
demotion, and the resulting motion history. It runs in a throwaway SQLite
database and evidence root that are discarded afterwards, and the rendered
captures back ``docs/paa-reviewer-walkthrough.md``.

Every capture is real CLI output: each step runs ``scout.cli.main.main``
end to end with ``sys.argv`` set to the command shown, so the JSON on
stdout, the error text on stderr, and the exit status are exactly what an
operator would see. Two things are pinned so the output is byte-reproducible
and publication-safe:

- ``paa_runtime.service``'s id and clock generators are replaced with
  counters, so motion ids, event ids, and timestamps are fixture values
  rather than fresh UUID4s and wall-clock instants;
- the throwaway evidence root's absolute path is rendered as
  ``<evidence-root>`` wherever the runtime echoes it, and evidence files
  are named by their repository-relative path.

Everything else — evidence hashes, event ordering, error text, the JSON
the CLI prints — is produced by the runtime unchanged. The evidence files
are the checked-in, redacted artifacts under ``evidence/paa/reference/``,
so no production identity, content, path, token, or operator name can
reach the rendered captures. Actor names are fixture values passed
explicitly with ``--actor``; the login-name fallback is never exercised.
"""

from __future__ import annotations

import contextlib
import io
import itertools
import json
import sys
import tempfile
from collections.abc import Callable, Iterator, Mapping, Sequence
from dataclasses import dataclass
from pathlib import Path
from unittest import mock

from paa_runtime import service as paa_service

from scout.cli import main as cli_main

REPO_ROOT = Path(__file__).resolve().parents[3]
CAPTURES_DIR = REPO_ROOT / "docs" / "assets" / "paa-walkthrough"
CAPTURE_SUFFIX = ".txt"
LABEL = "Reference execution"
TASK = "inbound_reply_surfacing"
EVIDENCE_ROOT_PLACEHOLDER = "<evidence-root>"
PROMOTION_EVIDENCE = Path("evidence/paa/reference/bundle/audit.json")
DEMOTION_PROPOSAL_EVIDENCE = Path("evidence/paa/reference/bundle/gate-block.json")

_HEADER = (
    f"Label: {LABEL}\n"
    "Generated by: scripts/generate_paa_walkthrough_captures.py\n"
    "Read first: docs/assets/paa-walkthrough/README.md\n"
)


@dataclass(frozen=True, slots=True)
class CliRun:
    """One CLI invocation and what it printed."""

    argv: tuple[str, ...]
    stdout: str
    stderr: str
    exit_code: int


@dataclass(frozen=True, slots=True)
class Capture:
    """One rendered capture file: a titled sequence of CLI runs and notes."""

    filename: str
    title: str
    intro: str
    parts: tuple[CliRun | str, ...]


class CaptureGenerationError(RuntimeError):
    """The scenario did not unfold as the generator expects."""


def _fixture_generators() -> Mapping[str, Callable[[], str]]:
    """Counter-backed replacements for the runtime's id and clock generators."""
    motion_counter = itertools.count(1)
    event_counter = itertools.count(1)
    clock = itertools.count(1)

    def new_motion_id() -> str:
        return f"00000000-0000-4000-8000-0000000{next(motion_counter):05d}"

    def new_event_id() -> str:
        return f"00000000-0000-4000-8000-0000ffff{next(event_counter):04d}"

    def new_created_at() -> str:
        tick = next(clock)
        return f"2026-01-01T00:{tick // 60:02d}:{tick % 60:02d}.000000Z"

    return {
        "new_motion_id": new_motion_id,
        "new_event_id": new_event_id,
        "new_created_at": new_created_at,
    }


class _Session:
    """A throwaway database and evidence root the CLI is pointed at."""

    def __init__(self, workdir: Path) -> None:
        self.db_path = workdir / "scout.db"
        self.evidence_root = workdir / "evidence-root"
        self.evidence_root.mkdir()

    def run(self, *argv: str) -> CliRun:
        stdout, stderr = io.StringIO(), io.StringIO()
        exit_code = 0
        with (
            mock.patch.object(sys, "argv", ["scout", *argv]),
            contextlib.redirect_stdout(stdout),
            contextlib.redirect_stderr(stderr),
        ):
            try:
                cli_main.main()
            except SystemExit as exc:
                exit_code = int(exc.code or 0)
        return CliRun(
            argv=tuple(argv),
            stdout=stdout.getvalue(),
            stderr=self._only_cli_errors(stderr.getvalue()),
            exit_code=exit_code,
        )

    def _only_cli_errors(self, text: str) -> str:
        """Keep the CLI's own ``paa <command> error:`` lines; drop log noise."""
        lines = [line for line in text.splitlines() if line.startswith("paa ")]
        return "\n".join(line.replace(str(self.evidence_root), EVIDENCE_ROOT_PLACEHOLDER)
                         for line in lines)

    def stored_evidence_path(self, evidence_ref: str) -> Path:
        return self.evidence_root / Path(evidence_ref)


@contextlib.contextmanager
def _pinned_runtime(session: _Session) -> Iterator[None]:
    generators = _fixture_generators()
    with contextlib.ExitStack() as stack:
        stack.enter_context(mock.patch.object(cli_main, "DB_PATH", str(session.db_path)))
        stack.enter_context(
            mock.patch.object(cli_main, "PAA_EVIDENCE_ROOT", session.evidence_root)
        )
        for name, replacement in generators.items():
            stack.enter_context(mock.patch.object(paa_service, name, replacement))
        yield


def _display_argv(argv: Sequence[str]) -> str:
    """The command as an operator would type it from the repository root."""
    parts = []
    for part in argv:
        text = part.replace(str(REPO_ROOT) + "/", "")
        parts.append(f'"{text}"' if " " in text else text)
    return "scout " + " ".join(parts)


def _expect(run: CliRun, *, exit_code: int) -> dict[str, object]:
    if run.exit_code != exit_code:
        raise CaptureGenerationError(
            f"{_display_argv(run.argv)} exited {run.exit_code}, expected {exit_code}: "
            f"{run.stderr or run.stdout}"
        )
    if exit_code != 0:
        return {}
    payload = json.loads(run.stdout)
    if not isinstance(payload, dict):
        raise CaptureGenerationError(f"{_display_argv(run.argv)} printed a non-object")
    return payload


def _scenario(session: _Session) -> list[Capture]:
    promotion_evidence = str(REPO_ROOT / PROMOTION_EVIDENCE)
    demotion_evidence = str(REPO_ROOT / DEMOTION_PROPOSAL_EVIDENCE)

    initial = session.run("paa", "show", TASK)
    initial_payload = _expect(initial, exit_code=0)
    if initial_payload.get("current_position") != "hitl":
        raise CaptureGenerationError("fresh database did not resolve to hitl")

    proposed = session.run(
        "paa", "propose", TASK, "--to", "hotl", "--evidence", promotion_evidence,
        "--actor", "operator-a",
        "--reason", "reference execution: phase1 audit window reviewed",
    )
    proposal = _expect(proposed, exit_code=0)
    motion_id = str(proposal["motion_id"])
    after_proposal = session.run("paa", "show", TASK)
    _expect(after_proposal, exit_code=0)

    approved = session.run(
        "paa", "approve", motion_id, "--actor", "operator-b",
        "--reason", "reference execution: second operator approved",
    )
    approval = _expect(approved, exit_code=0)
    if approval.get("status") != "executed":
        raise CaptureGenerationError("approval did not execute the motion")
    at_hotl = session.run("paa", "show", TASK)
    if _expect(at_hotl, exit_code=0).get("current_position") != "hotl":
        raise CaptureGenerationError("approval did not move the position to hotl")

    stale = session.run(
        "paa", "propose", TASK, "--to", "hitl", "--evidence", demotion_evidence,
        "--actor", "operator-a",
        "--reason", "reference execution: blocking evaluator fired",
    )
    stale_proposal = _expect(stale, exit_code=0)
    stale_id = str(stale_proposal["motion_id"])
    stored = session.stored_evidence_path(str(stale_proposal["evidence_ref"]))
    stored.write_bytes(stored.read_bytes() + b"\n")

    tampered = session.run(
        "paa", "approve", stale_id, "--actor", "operator-b",
        "--reason", "reference execution: attempted approval",
    )
    _expect(tampered, exit_code=1)
    if "tampered" not in tampered.stderr:
        raise CaptureGenerationError(f"expected a tamper error, got: {tampered.stderr!r}")
    still_hotl = session.run("paa", "show", TASK)
    if _expect(still_hotl, exit_code=0).get("current_position") != "hotl":
        raise CaptureGenerationError("a failed approval changed the position")
    rejected = session.run(
        "paa", "reject", stale_id, "--actor", "operator-b",
        "--reason", "reference execution: evidence no longer matches its recorded hash",
    )
    if _expect(rejected, exit_code=0).get("status") != "rejected":
        raise CaptureGenerationError("rejection did not record")

    demoted = session.run(
        "paa", "demote", TASK, "--actor", "oncall",
        "--reason", "reference execution: blocking evaluator fired",
        "--source-row", "gate_blocks:1",
    )
    if _expect(demoted, exit_code=0).get("status") != "executed":
        raise CaptureGenerationError("demotion did not execute")
    back_at_hitl = session.run("paa", "show", TASK)
    if _expect(back_at_hitl, exit_code=0).get("current_position") != "hitl":
        raise CaptureGenerationError("demotion did not return the position to hitl")

    history = session.run("paa", "list", "--task", TASK)
    _expect(history, exit_code=0)

    return [
        Capture(
            filename="01-initial-position.txt",
            title="Initial position: hitl, folded from an empty event stream",
            intro=(
                "A fresh database holds no autonomy events, so the resolved position is "
                "the declaration's initial_position. Nothing is stored as \"current "
                "position\"; the value is recomputed from the declaration and the event "
                "stream on every call. The checked-in declaration lists no scopes, so "
                "scope resolves as null."
            ),
            parts=(initial,),
        ),
        Capture(
            filename="02-promotion-proposal.txt",
            title="Promotion proposal: one motion_proposed event, no change in position",
            intro=(
                "The proposal binds itself to the exact bytes of one evidence file, here "
                "the redacted phase1 audit from the checked-in reference bundle, and "
                "records their sha256. Position is unchanged until a different operator "
                "approves."
            ),
            parts=(proposed, after_proposal),
        ),
        Capture(
            filename="03-approved-motion-and-hotl-position.txt",
            title="Approval: motion_approved and position_changed commit together",
            intro=(
                "Approval re-verifies the evidence bytes against the recorded hash, "
                "reloads the declaration, re-checks the transition, and confirms no "
                "position change intervened since the proposal, all inside one write "
                "transaction. Only then does it insert both events. The position now "
                "folds to hotl and names the event that moved it."
            ),
            parts=(approved, at_hotl),
        ),
        Capture(
            filename="04-evidence-verification-failure.txt",
            title="Failure path: approval fails closed on tampered evidence",
            intro=(
                "A second motion proposes the declared demotion, binding the redacted "
                "gate-block artifact as its evidence. The generator then appends one "
                "byte to the stored evidence file, standing in for any modification "
                "after proposal. Approval re-hashes the bytes, finds the mismatch, and "
                "writes nothing: the motion stays proposed and the position stays hotl. "
                "The operator then rejects the stale motion; rejection is terminal."
            ),
            parts=(
                stale,
                "The stored evidence file is modified here, outside the CLI.",
                tampered,
                still_hotl,
                rejected,
            ),
        ),
        Capture(
            filename="05-immediate-demotion.txt",
            title="Immediate demotion: propose, approve, and execute in one step",
            intro=(
                "The declared demotion (hotl to hitl) needs no review round-trip. "
                "demote generates canonical JSON evidence from its own arguments, "
                "content-addresses it, and inserts motion_proposed, motion_approved, "
                "and position_changed in one transaction. It refuses to run unless the "
                "current position equals the declared demotion source."
            ),
            parts=(demoted, back_at_hitl),
        ),
        Capture(
            filename="06-motion-history.txt",
            title="Motion history: status is a projection of the event stream",
            intro=(
                "list derives each motion's status from its events: executed when "
                "position_changed exists, rejected when motion_rejected exists, "
                "proposed otherwise. Nothing here is stored as a status column."
            ),
            parts=(history,),
        ),
    ]


def _render_run(run: CliRun) -> str:
    lines = [f"$ {_display_argv(run.argv)}"]
    if run.stdout:
        lines.append(run.stdout.rstrip("\n"))
    if run.stderr:
        lines.append(run.stderr.rstrip("\n"))
    if run.exit_code != 0:
        lines.append(f"[exit status {run.exit_code}]")
    return "\n".join(lines) + "\n"


def _render_capture(capture: Capture) -> str:
    body = [f"{_HEADER}\n# {capture.title}\n\n{capture.intro}\n"]
    for part in capture.parts:
        body.append(f"\n{part}\n" if isinstance(part, str) else "\n" + _render_run(part))
    return "".join(body)


def render_captures() -> dict[str, str]:
    """Render every capture as ``{filename: text}`` with no lasting side effects."""
    with tempfile.TemporaryDirectory(prefix="paa-walkthrough-") as tmp:
        session = _Session(Path(tmp))
        with _pinned_runtime(session):
            captures = _scenario(session)
    return {capture.filename: _render_capture(capture) for capture in captures}


def _managed_files(target_dir: Path) -> dict[str, str]:
    """The managed captures on disk, read as exact UTF-8 bytes.

    Byte reads and writes on purpose: ``Path.read_text`` would fold CRLF
    into LF and use the locale encoding, which is exactly the drift the
    check exists to catch.
    """
    if not target_dir.is_dir():
        return {}
    return {
        path.name: path.read_bytes().decode("utf-8")
        for path in sorted(target_dir.iterdir())
        if path.is_file() and path.suffix == CAPTURE_SUFFIX
    }


def write_captures(target_dir: Path = CAPTURES_DIR) -> list[str]:
    """Replace the managed ``*.txt`` captures under *target_dir*; return their names."""
    rendered = render_captures()
    target_dir.mkdir(parents=True, exist_ok=True)
    for stale in set(_managed_files(target_dir)) - set(rendered):
        (target_dir / stale).unlink()
    for filename, text in rendered.items():
        (target_dir / filename).write_bytes(text.encode("utf-8"))
    return sorted(rendered)


def check_captures(target_dir: Path = CAPTURES_DIR) -> list[str]:
    """Problems that make *target_dir* differ from a fresh render; empty when current."""
    rendered = render_captures()
    on_disk = _managed_files(target_dir)
    problems = [f"missing capture: {name}" for name in sorted(set(rendered) - set(on_disk))]
    problems += [f"unexpected capture: {name}" for name in sorted(set(on_disk) - set(rendered))]
    problems += [
        f"stale capture: {name}"
        for name in sorted(set(rendered) & set(on_disk))
        if rendered[name] != on_disk[name]
    ]
    return problems


__all__ = [
    "CAPTURES_DIR",
    "Capture",
    "CaptureGenerationError",
    "CliRun",
    "LABEL",
    "check_captures",
    "render_captures",
    "write_captures",
]
