"""CLI wrapper around grading_corpus_export.export_grading_corpus.

Thin by design: argument parsing, reporting, and exit-code translation
only. The read-only source boundary, the copy, verification, and the
atomic replace all live in grading_corpus_export.

Run this before resetting Scout's database onto the paa_runtime schema.
Everything else in that database can be regenerated by running the
pipeline again; the grading judgments cannot.
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

# Support both documented forms:
#   python -m scripts.export_grading_corpus
#   python scripts/export_grading_corpus.py
sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from scout.config import DB_PATH
from scout.grading.corpus_export import GradingExportError, export_grading_corpus


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        description="Export the grading corpus to a standalone SQLite file.",
    )
    parser.add_argument(
        "destination",
        help="path to write the export to (replaced atomically on success)",
    )
    parser.add_argument(
        "--db", default=DB_PATH, help=f"source database (default: {DB_PATH})",
    )
    args = parser.parse_args(argv)

    try:
        result = export_grading_corpus(args.db, args.destination)
    except GradingExportError as exc:
        print(f"export-grading-corpus error: {exc}", file=sys.stderr)
        return 2

    width = max(len(table.name) for table in result.tables)
    for table in result.tables:
        print(f"  {table.name:<{width}}  {table.row_count:>9,}")
    print(f"\n{result.total_rows:,} rows -> {result.destination}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
